config/routes.rb
Rails.application.routes.draw do
  
  resources :transfers
  resources :balances
  resources :expense_plans
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :expenses
  resources :receipts


  get "/statistics/" => "statistics#show"
  get "/statistics/:page" => "statistics#show"

  root to: 'expenses#index'
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :account

  def account_name()
    account.try(:name)
  end

end

app/controllers/balances_controller.rb
class BalancesController < InheritedResources::Base
  before_action :set_balance, only: [:show, :edit, :update, :destroy]
  before_action :fill_values, only: [:edit, :new, :index, :create]
  before_action :authenticate_user! 

  def index
    today = Date.today
    @month = t(today.try('strftime',"%B")) + " " + today.try('strftime',"%Y")
    period = today.beginning_of_month..today.end_of_month
    @balances = Balance.where(date: period)
    @balances = @balances.map{|balance| 
      exp = Expense.where(date: period, account_id: balance.account_id).sum(:amount)
      exp_t = Transfer.where(date: period, account_id: balance.account_id).sum(:amount)
      
      rec = Receipt.where(date: period, account_id: balance.account_id).sum(:amount)
      rec_t = Transfer.where(date: period, account_to_id: balance.account_id).sum(:amount)
      {
      id: balance.id,
      account: balance.account.try(:name),
      balance_start: balance.amount,
      expenses: exp + exp_t,
      receipts: rec + rec_t,
      balance_end: balance.amount.try(:to_i) - exp - exp_t + rec + rec_t

    }}

    puts "@balances #{@balances}"
  end

  def new
    @balance = Balance.new
    @balance.date = Date.today.beginning_of_month
  end

  def create
    @balance = Balance.new(balance_params)

    respond_to do |format|
      if @balance.save
        format.html { redirect_to balances_url, notice: 'Баланс успешно сохранен.' }
        format.json { render :show, status: :created, location: @balance }
      else
        format.html { render :new }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @balance.update(balance_params)
        format.html { redirect_to balances_url, notice: 'Баланс успешно обновлен.' }
      else
        flash.now[:danger] = @balance.errors.full_messages
        format.html { render :edit }
      end
    end

  end


  private
    def set_balance 
      @balance = Balance.find(params[:id])
    end

    def fill_values
      @accounts = Account.order(:name)
    end

    def balance_params
      params.require(:balance).permit(:date, :amount, :account_id)
    end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<div class="balance_form">
<%= form_with(model: balance, local: true) do |form| %>
  <div class="field table_row begin_of_month">
    <div style="width: 150px; float: left; margin-right: 10px">
    <%= form.label "Месяц" %>
    <%= form.text_field :date, label: false, class: "txt datepicker left" %>
    </div>

    <div class="left" style="width: 250px;  margin-right: 10px">
    <%= form.label "Сумма" %>
    <%= form.number_field :amount %>
    </div>

  </div>

  <div class="field table_row">
    <div class="table_cell">
      <label>Счет</label>
      <v-chosen name="account" placeholder="Счет..."/>
    </div>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>


<%= render 'form_vue' %>

app/views/balances/_form_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.balance_form',
    data: <%= fill_vue_data(@balance, {
      model: 'balance',
      lists: 'accounts',
      list_values: 'account'
    })%>
  })


</script>

app/views/balances/_index_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.balances',
    data: <%= fill_vue_data(nil, { 
      sortKey: 'sortdate',
      reverse: true,
      currentIndex: -1,
      currentMonth: -1,
      confirmModal: false,
      
      total_end: 0,
      total_e: 0,
      total_r: 0,

      groupHeaders: [],
      filter: [],
      grouped: [],
      filteredData: [],
      list_values: 'account',
      lists: 'accounts balances:raw@balances',
      columns: [ ['account', 'Счет'], ['balance_start', 'Нач. ост.'], ['expenses', 'Расходы'], ['receipts', 'Поступления'],
                 ['balance_end', 'Кон. ост'], ['comment', 'Комментарий']]
      
    }) %>,

    updated(){
      this.onInput();
    },

    mounted(){
      this.$root.$on('onInput', this.onInput);
      this.$root.$on('modalYes', this.modalYes);
    },

  methods:{
    cellClass(column, value){
      cls = ''

      let columnIsDigit = (column == true);
      if (!columnIsDigit){
        let ind = this.columns.indexOf(column);
        if (ind <5 && ind >0) columnIsDigit = true;
        
      }
      if (columnIsDigit) {
        cls = cls + 'td_right';
        if (value<0) cls = cls + " red";
      }

      return cls;
    },

    formatValue(value, column){
      let ind = this.columns.indexOf(column);
      if (ind <5 && ind >0) {
        return to_sum(value)
      }
      return value
    },  

    fSum(sum){
      return to_sum(sum)
    },

    fCalcTotal(){
      // console.log('fCalcTotal: m', m, 'this.grouped[m]', this.grouped[m])
      var arr = this.balances;
      let total_end = 0;
      let total_e = 0;
      let total_r = 0;

      total = 0;
      for (i = 0; i < arr.length; ++i) {
        total = total + toInt(arr[i].balance_start);
        total_end = total_end + toInt(arr[i].balance_end);
        total_e = total_e + toInt(arr[i].expenses);
        total_r = total_r + toInt(arr[i].receipts);
      }
      this.total_end = total_end;
      this.total_e = total_e;
      this.total_r = total_r;
      return to_sum(total);
    },


    onInput(e){
      if (e !== undefined){
        let s = -1;
        for (var i=0; i < this.filter.length; i++){
          if (this.filter[i].field === e.name) {s = i;}
        }

        if (s > -1){
          if (e.label === undefined)
            this.filter.splice(s,1)
          else
            this.filter[s].value = e.label
        } 
        else if (e.label !== undefined)
          this.filter.push({field: e.name, value: e.label});
      // console.log('input', e, this.filter) 
      // this.fGroup();
      }
    },
    
    fSort(arr){
       var vm = this
        let s = this.reverse ? 1 : -1
        let ns = this.reverse ? -1 : 1

        // console.log('fSort', this.grouped, arr)

        this.filteredData = arr.sort((a,b) => 
          (a[this.sortKey] > b[this.sortKey]) ? ns : ((b[this.sortKey] > a[this.sortKey]) ? s : 0));
        

        if (this.filter.length > 0){
          this.filteredData = this.filteredData.filter(function (item) {
            for (q in vm.filter) {
              let f = vm.filter[q]
              if (item[f.field].toLowerCase().indexOf(f.value.toLowerCase()) === -1) return false
            }
            return true
          })
        } else {
          // this.fGroup();
          return this.filteredData;
        }
        // this.fGroup();
        return this.filteredData;
      
    },

    sortBy(sortKey) {
      if (sortKey == 'date') sortKey = 'sortdate'
      this.reverse = (this.sortKey == sortKey) ? ! this.reverse : false;
      this.sortKey = sortKey;
      this.fSort(this.balances);
    },

    shuffle: function () {
      this.sortBy("sortdate")
      this.reverse = true;
      this.filter = [];
    },

    editLink(id){
      return "/balances/" + id + "/edit"
    },

    modalYes(){
      if (this.currentIndex === '' || !this.confirmModal ) return;
      // let exp = this.grouped[this.currentMonth];
      let index = this.balances.indexOf(this.currentIndex);
      // console.log('modalYes', index, 'this.currentIndex', this.currentIndex, 'this.currentMonth', this.currentMonth);

      if (index<0) return;
      this.balances.splice(index, 1);
      delete_item('/balances/'+this.currentIndex.id);
      // this.fGroup();
    },


    deleteRow(index){
        // this.currentMonth = month;
        this.currentIndex = index;
        this.confirmModal = true;
        // console.log('this.confirmModal' ,this.confirmModal);
    },

    deleteLink(id){
      return "/balances/" + id 
    }


  }

})


</script>

app/views/balances/edit.html.erb
<h1>Редактирование баланса</h1>

<%= render 'form', balance: @balance %>

app/views/balances/index.html.slim
.head
  | Балансы  
  = link_to 'Добавить баланс', new_balance_path, class: 'btn btn_a right'

.balances
  .table_filter
    div
      v-chosen name="account" placeholder="Счет..." 

  .expenses_table
    .grid_title 
      =@month

    .table_balances_col.grid_thead
      div v-for="column in columns"
        a href="#" v-on:click="sortBy(column[0])" {{ column[1] }}

    transition-group name="flip-list" tag="ul" 
      li v-bind:key="item.id" v-for="item in balances"
        .table_balances_col
          div :class="cellClass(column, item[column[0]])" v-for="column in columns"
            | {{ formatValue(item[column[0]], column) }}
          .edit_delete.td_right style="" 
            a.icon.icon_edit :href="editLink(item.id)" data-modal="true"   
            span.icon.icon_remove @clickgbvhbn="deleteRow(item)"

    .table_balances_col.grid_total
      div Итого:
      .td_right  
        |{{fCalcTotal()}}
      .td_right  
        |{{fSum(total_e)}}
      .td_right  
        |{{fSum(total_r)}}
      div :class="cellClass(true, total_end)"  
        |{{fSum(total_end)}}

= render 'shared/modal_delete'
= render 'index_vue'

app/views/balances/new.html.erb
<h1>Новый баланс</h1>

<%= render 'form', balance: @balance %>

app/views/balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @balance.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @balance.amount %>
</p>

<p>
  <strong>Account:</strong>
  <%= @balance.account %>
</p>

<%= link_to 'Edit', edit_balance_path(@balance) %> |
<%= link_to 'Back', balances_path %>