config/routes.rb
Rails.application.routes.draw do
  
  resources :transfers
  resources :balances
  resources :expense_plans
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :expenses
  resources :receipts


  get "/statistics/" => "statistics#show"
  get "/statistics/:page" => "statistics#show"

  root to: 'expenses#index'
end

app/models/expense_plan.rb
class ExpensePlan < ApplicationRecord
  belongs_to :expense_type

  def expense_type_name()
    expense_type.try(:name)
  end

end

app/controllers/expense_plans_controller.rb
class ExpensePlansController < InheritedResources::Base
  before_action :set_expense_plan, only: [:show, :edit, :update, :destroy]
  before_action :fill_values, only: [:edit, :new, :index, :create]
  before_action :authenticate_user!


  def new
    @expense_plan = Balance.new
    @expense_plan.date = Date.today.beginning_of_month
  end


  def create
    @expense_plan = ExpensePlan.new(expense_plan_params)

    respond_to do |format|
      if @expense_plan.save
        format.html { redirect_to expense_plans_url, notice: 'План успешно сохранен.' }
        format.json { render :show, status: :created, location: @expense_plan }
      else
        format.html { render :new }
        format.json { render json: @expense_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expense_plan.update(expense_plan_params)
        format.html { redirect_to expense_plans_url, notice: 'План успешно обновлен.' }
      else
        flash.now[:danger] = @expense_plan.errors.full_messages
        format.html { render :edit }
      end
    end

  end


  private

    def set_expense_plan
      @expense_plan = ExpensePlan.find(params[:id])
    end

    def expense_plan_params
      params.require(:expense_plan).permit(:date, :amount, :expense_type_id, :comment)
    end

    def fill_values
      @expense_types = ExpenseType.order(:name)
    end

end

app/helpers/expense_plans_helper.rb
module ExpensePlansHelper
end

app/views/expense_plans/_form.html.erb
<div class="expense_plan">
<%= form_with(model: expense_plan, local: true) do |form| %>
  <% if expense_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense_plan.errors.count, "error") %> prohibited this expense_plan from being saved:</h2>

      <ul>
      <% expense_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field table_row begin_of_month">
    <div style="width: 150px; float: left; margin-right: 10px">
    <%= form.label "Месяц" %>
    <%= form.text_field :date, label: false, class: "txt datepicker left" %>
    </div>

    <div class="left" style="width: 250px;  margin-right: 10px">
    <%= form.label "Сумма" %>
    <%= form.number_field :amount %>
    </div>
  </div>

  <div class="field table_row">
    <div class="table_cell">
      <label>Категория</label>
      <v-chosen name="expense_type" placeholder="Категория..."/>
    </div>
  </div>

  <div class="field">
    <label>Комментарий</label>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

<%= render 'form_vue' %>

app/views/expense_plans/_form_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.expense_plan',
    data: <%= fill_vue_data(@expense_plan, {
      model: 'expense_plan',
      lists: 'expense_types',
      list_values: 'expense_type'
    })%>
  })


</script>

app/views/expense_plans/edit.html.erb
<h1>Редактирование плана расход</h1>

<%= render 'form', expense_plan: @expense_plan %>

app/views/expense_plans/index.html.erb
<p id="notice"><%= notice %></p>

<div class="head">  
  Плановые расходы 
<%= link_to 'Добавить план', new_expense_plan_path, class: 'btn btn_a right' %>
</div>



<table>
  <thead>
    <tr>
      <th>Месяц</th>
      <th>Сумма</th>
      <th>Категория</th>
      <th>Комментарий</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @expense_plans.each do |expense_plan| %>
      <tr>
        <td><%= expense_plan.date %></td>
        <td><%= expense_plan.amount %></td>
        <td><%= expense_plan.expense_type_name %></td>
        <td><%= expense_plan.comment %></td>
        <td><%= link_to 'Edit', edit_expense_plan_path(expense_plan) %></td>
        <td><%= link_to 'Destroy', expense_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/expense_plans/new.html.erb
<h1>Новый план расхода</h1>

<%= render 'form', expense_plan: @expense_plan %>

app/views/expense_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @expense_plan.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense_plan.amount %>
</p>

<p>
  <strong>Expense type:</strong>
  <%= @expense_plan.expense_type %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @expense_plan.comment %>
</p>

<%= link_to 'Edit', edit_expense_plan_path(@expense_plan) %> |
<%= link_to 'Back', expense_plans_path %>