config/routes.rb
Rails.application.routes.draw do
  
  resources :transfers
  resources :balances
  resources :expense_plans
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :expenses
  resources :receipts


  get "/statistics/" => "statistics#show"
  get "/statistics/:page" => "statistics#show"

  root to: 'expenses#index'
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :account
  belongs_to :account_to, class_name: "Account", foreign_key: :account_to_id


  def account_name()
    account.try(:name)
  end

  def account_to_name()
    account_to.try(:name)
  end


end

app/controllers/transfers_controller.rb
class TransfersController < InheritedResources::Base
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  before_action :fill_values, only: [:edit, :new, :index, :create]
  before_action :authenticate_user! 

  def index
    @transfers = Transfer.order(date: :desc)
    @json_transfers = @transfers.map{|e| {
      id: e.id, 
      date: e.date.try('strftime',"%d.%m.%Y"),
      sortdate: e.date,
      month: t(e.date.try('strftime',"%B")) + " " + e.date.try('strftime',"%Y"),
      amount: e.amount,
      account: e.account_name,
      account_to: e.account_to_name,
      comment: e.comment
    }}

  end

  def new
    if params[:from]
      from = Transfer.find(params[:from])
      attrs = from.attributes.except!([:id, :created_at, :updated_at, :user_id])
      @transfer = Transfer.new(attrs)
    else
      @transfer = Transfer.new
    end
    @transfer.date = Date.today
  end

  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to transfers_url, notice: 'Баланс успешно сохранен.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to transfers_url, notice: 'Баланс успешно обновлен.' }
      else
        flash.now[:danger] = @transfer.errors.full_messages
        format.html { render :edit }
      end
    end

  end


  private
    def set_transfer 
      @transfer = Transfer.find(params[:id])
    end

    def fill_values
      @accounts = Account.order(:name)
    end

    def transfer_params
      params.require(:transfer).permit(:date, :amount, :account_id, :account_to_id, :comment)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<div class='transfer_form'>
<%= form_with(model: transfer, local: true) do |form| %>
<% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field table_row">
    <div style="width: 150px; float: left; margin-right: 10px">
      <label> Дата</label>
      <%= form.text_field :date, label: false, class: "txt datepicker left" %>
    </div>

    <div class="left" style="width: 250px;  margin-right: 10px">
      <label> Сумма</label>
      <%= form.number_field :amount %>
    </div>
  </div>

  <div class="field">
    <label> Счет отправитель</label>
    <v-chosen name="account" placeholder="Счет..."/>
  </div>

  <div class="field">
    <label> Счет получатель</label>
    <v-chosen name="account_to" placeholder="Счет..."/>
  </div>

  <div class="field">
    <label>Комментарий</label>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= submit_cancel transfers_url, {disabled: "!f_valid"} %>
  </div>

<% end %>
</div>


<%= render 'form_vue' %>

app/views/transfers/_form_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.transfer_form',
    data: <%= fill_vue_data(@transfer, {
      model: 'transfer',
      lists: 'accounts account_tos:@accounts',
      list_values: 'account account_to'
    })%>
  })


</script>

app/views/transfers/_index_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.transfers', 
    mixins: [m_created, m_index],
    data: <%= fill_vue_data(nil, { 
      sortKey: 'sortdate',
      controller: 'transfers',
      reverse: true,
      currentIndex: -1,
      currentMonth: -1,
      confirmModal: false,
      groupHeaders: [],
      filter: [],
      grouped: [],
      filteredData: [],
      list_values: 'shop account',
      lists: 'shops accounts users mainList:raw@json_transfers',
      columns: [['date', 'Дата'], ['amount', 'Сумма'],
                ['account', 'Счет отпр.'], ['account_to', 'Счет получ.'],
                ['comment', 'Комментарий']]
      
    }) %>,
})
</script>

app/views/transfers/edit.html.erb
<h1>Редактирование перемещения</h1>

<%= render 'form', transfer: @transfer %>

app/views/transfers/index.html.slim
.head
  | Перемещения
  = link_to 'Добавить перемещение', new_transfer_path, class: 'btn btn_a right'

.ower  
  .transfers

    = render 'shared/index'
    = render 'shared/modal_delete'
= render 'index_vue'



table
  thead
    tr
      th Date
      th Amount
      th Account from
      th Account to
      th Comment
      th colspan="3" 
  tbody
    - @transfers.each do |transfer|
      tr
        td= transfer.date
        td= transfer.amount
        td= transfer.account.try(:name)
        td= transfer.account_to.try(:name)
        td= transfer.comment
        td= link_to 'Show', transfer
        td= link_to 'Edit', edit_transfer_path(transfer)
        td= link_to 'Destroy', transfer, method: :delete, 'data-confirm' => "Are you sure?"

app/views/transfers/new.html.erb
<h1>Новое перемещение</h1>

<%= render 'form', transfer: @transfer %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @transfer.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transfer.amount %>
</p>

<p>
  <strong>Account from:</strong>
  <%= @transfer.account_from %>
</p>

<p>
  <strong>Account to:</strong>
  <%= @transfer.account_to %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @transfer.comment %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>