config/routes.rb
Rails.application.routes.draw do
  
  resources :transfers
  resources :balances
  resources :expense_plans
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :expenses
  resources :receipts


  get "/statistics/" => "statistics#show"
  get "/statistics/:page" => "statistics#show"

  root to: 'expenses#index'
end

app/controllers/expenses_controller.rb
class ExpensesController < InheritedResources::Base
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :fill_values, only: [:edit, :new, :index, :create]
  before_action :authenticate_user!
  before_action :check_amount, only: [:create, :update]

  def index
    @expenses = Expense.order(date: :desc).joins(:shop)
    @json_expenses = @expenses.map{|e| {
      id: e.id, 
      date: e.date.try('strftime',"%d.%m.%Y"),
      sortdate: e.date,
      month: t(e.date.try('strftime',"%B")) + " " + e.date.try('strftime',"%Y"),
      shop: e.shop_name,
      amount: e.amount,
      account: e.account_name,
      expense_type: e.expense_type_names,
      expense_kind: e.expense_kind_name,
      user: e.user_name,
      comment: e.comment
    }}

  end

  def new
    # fill_values
    if params[:from]
      from = Expense.find(params[:from])
      attrs = from.attributes.except!([:id, :created_at, :updated_at, :user_id])
      @expense = Expense.new(attrs)
    else
      @expense = Expense.new
    end

    @user = current_user
    @expense.date = Date.today
  end

  def edit
    # puts @expense.account
  end


  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to expenses_url, notice: 'Расход успешно сохранен.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expenses_url, notice: 'Расход успешно обновлен.' }
      else
        flash.now[:danger] = @expense.errors.full_messages
        format.html { render :edit }
      end
    end
  end

  def destroy
    @expense.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    def set_expense
      @expense = Expense.find(params[:id])
    end

    def fill_values
      @shops = Shop.order(:name)
      @accounts = Account.order(:name)
      @expense_types = ExpenseType.order(:name)
      @expense_kinds = ExpenseKind.order(:name)
      @users = User.order(:username)
      @rows = @expense.expense_rows if @expense.present?
    end

    def check_amount
      expense_params[:amount] = expense_params[:amount].gsub!(' ','') if !expense_params[:amount].nil?
    end

    def expense_params
      params.require(:expense).permit(:date, :shop_id, :amount, :report_amount,
                                      :account_id, :expense_type_id, :user_id, :comment,
                                      expense_rows_attributes: [:id, :expense_type_id, :amount, :comment, :_destroy])
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.slim
.expense
  = form_with(model: expense, local: true) do |form|
    .panel_left.w35
      .field.table_row
        div style=("width: 150px; float: left; margin-right: 10px") 
          label Дата
          = form.text_field :date, label: false, class: "txt datepicker left"
        .left style=("width: 155px;") 
          label Сумма
          m-number name="amount", "@input"=>"onInput()"
      .field.table_row
        div
          = form.label t :shop_id
          v-chosen name="shop" placeholder="Магазин..." 
      .field.table_row
        div
          label Категория
          v-chosen name="expense_type" placeholder="Категория..." 
      .field
        label Счет
        v-chosen name="account" placeholder="Счет..." 
      .field
        label Ответственный
        v-chosen name="user" placeholder="Кто..." 
      .field
        label Комментарий
        = form.text_field :comment
      .actions
        = submit_cancel expenses_url, {classValid: '!formValid', tip: 'noteValid', click: 'onSubmit'}
    .panel_right.w60
      #e_rows.shops.before_30
        = render 'rows'
= render 'form_vue'

app/views/expenses/_form_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.expense',
    mixins: [m_created],
    data: <%= fill_vue_data(@expense, {
      formValid: false,
      rowValid: false,
      noteValid: 'test note',
      model: 'expense',
      required: ['shop', 'expense_type', 'amount', 'account', 'user'],
      texts: 'amount comment new_comment new_amount new_expense_type',
      lists: 'shops accounts expense_types users new_expense_types:@expense_types',
      list_values: 'shop account expense_type user',
      expense_rows:  @expense.expense_rows.map{|s| { id: s.id,
                  expense_type: {label: s.expense_type_name, value: s.expense_type_id}, 
                  amount: s.amount, comment: s.comment,
                  _destroy: false}} 
    })%>,

    methods: {
      row_field(index, field) {
        return "expense[expense_rows_attributes]["+index+"]["+field+']'
      },

      add_row(){
        if (this.new_expense_type !== null){
          this.expense_rows.push({expense_type: this.new_expense_type, 
                                  amount: this.new_amount, 
                                  comment: this.new_comment, 
                                  _destroy: false})
          this.new_expense_type = null
          this.new_amount = 0
          this.new_comment = "" 
          this.onInput();

          this.calcTotal();
        }
      },

      calcTotal(){
        let amount =0
        this.expense_rows.filter(sh => !sh._destroy).forEach( r =>{
          amount = amount + toInt(r.amount)
        })
        this.amount = amount
      },

      del_row(index){
        this.expense_rows[index]['_destroy'] = true
        this.calcTotal();
      },

      onInput(e){
        if (e == undefined) return;
        rowValid = true
        formValid = true
        noteValid = ''
        
        if (e.name == 'amount' && !v_nil(this.new_expense_type)){
          let rest = this.amount
          let amount =0
          this.expense_rows.filter(sh => !sh._destroy).forEach( r =>{
            amount = amount + toInt(r.amount)
          })
          this.new_amount = this.amount - amount
        } 

        if (v_nil(this.new_expense_type)) {
          rowValid = false
        } else {
          formValid = false
          noteValid = 'Есть не сохраненные данные строки расхода'
        }

        if (v_nil(this.new_amount)){
          rowValid = false
        } else {
          formValid = false
          noteValid = 'Есть не сохраненные данные строки расхода'
        }

        this.required.forEach( c => {if (v_nil(this[c])) formValid = false} );
        this.rowValid  = rowValid
        this.formValid = formValid
        this.noteValid = noteValid
      },

      onSubmit(event){
        if (event && !this.formValid) {
          event.preventDefault();
          if (rowValid){
            this.add_row();
          } else {

          show_ajax_message(this.noteValid, 'error');
          }
        }

      }


    }

  })


</script>

app/views/expenses/_index_vue.html.erb
<script>
  Vue.component('v-select', VueSelect.VueSelect)

  let app = new Vue({
    el: '.expenses', 
    mixins: [m_created],
    data: <%= fill_vue_data(nil, { 
      sortKey: 'sortdate',
      reverse: true,
      currentIndex: -1,
      currentMonth: -1,
      confirmModal: false,
      groupHeaders: [],
      filter: [],
      grouped: [],
      filteredData: [],
      list_values: 'shop account expense_type',
      lists: 'shops accounts expense_types expense_kinds users expenses:raw@json_expenses',
      columns: [['date', 'Дата'], ['shop', 'Магазин'], ['amount', 'Сумма'],
                ['account', 'Счет'], ['expense_type', 'Категория'], ['user', 'Кто'], 
                ['comment', 'Комментарий']]
      
    }) %>,

    updated(){
      this.onInput();
    },

    created(){
      this.fGroup();
      this.$root.$on('onInput', this.onInput);
      this.$root.$on('modalYes', this.modalYes);
    },

    mounted(){
    },



    computed: {
      calcTotal: function () { 
        total = 0;
        for (i = 0; i < this.filteredData.length; ++i) {
          total = total + this.filteredData[i].amount;
        }
        return to_sum(total);
      },

      computedList(){
        var vm = this
        let s = this.reverse ? 1 : -1
        let ns = this.reverse ? -1 : 1
        console.log('computedList')
        this.filteredData = this.expenses.sort((a,b) => 
          (a[this.sortKey] > b[this.sortKey]) ? ns : ((b[this.sortKey] > a[this.sortKey]) ? s : 0));

        if (this.filter.length > 0){
          this.filteredData = this.filteredData.filter(function (item) {
            for (q in vm.filter) {
              let f = vm.filter[q]
              if (item[f.field].toLowerCase().indexOf(f.value.toLowerCase()) === -1) return false
            }
            return true
          })
        } else {
          return this.filteredData;
        }
        return this.filteredData;
      },
    },

  methods:{

    fCalcTotal(m){
      // console.log('fCalcTotal: m', m, 'this.grouped[m]', this.grouped[m])
      var arr = this.grouped[m];
        total = 0;
        for (i = 0; i < arr.length; ++i) {
          total = total + arr[i].amount;
        }
        return to_sum(total);
    },

    onInput(e){
      if (e !== undefined){
        let s = -1;
        for (var i=0; i < this.filter.length; i++){
          if (this.filter[i].field === e.name) {s = i;}
        }

        if (s > -1){
          if (e.label === undefined)
            this.filter.splice(s,1)
          else
            this.filter[s].value = e.label
        } 
        else if (e.label !== undefined)
          this.filter.push({field: e.name, value: e.label});
      // console.log('input', e, this.filter) 
      this.fGroup();
      }
    },
    
    fGroup(){
      this.grouped = _.groupBy(this.expenses, 'month')
      this.groupHeaders  = Object.keys(this.grouped)
      for (i = 0; i < this.groupHeaders.length; ++i) { 

        this.grouped[this.groupHeaders[i]] = this.fSort(this.grouped[this.groupHeaders[i]]);
        // console.log('a', a);
      }
    },

    fSort(arr){
       var vm = this
        let s = this.reverse ? 1 : -1
        let ns = this.reverse ? -1 : 1

        this.filteredData = arr.sort((a,b) => 
          (a[this.sortKey] > b[this.sortKey]) ? ns : ((b[this.sortKey] > a[this.sortKey]) ? s : 0));

        if (this.filter.length > 0){
          this.filteredData = this.filteredData.filter(function (item) {
            for (q in vm.filter) {
              let f = vm.filter[q]
              let v = item[f.field]

              if (v == null || v.toLowerCase().indexOf(f.value.toLowerCase()) === -1) return false
            }
            return true
          })
        } else {
          return this.filteredData;
        }
        return this.filteredData;
      
    },

    sortBy(sortKey, month) {
      if (sortKey == 'date') sortKey = 'sortdate'
      this.reverse = (this.sortKey == sortKey) ? ! this.reverse : false;
      this.sortKey = sortKey;
      this.fSort(this.grouped[month]);
    },

    shuffle: function () {
      this.sortBy("sortdate")
      this.reverse = true;
      this.filter = [];
    },

    editLink(id){
      return "/expenses/" + id + "/edit"
    },

    modalYes(){
      if (this.currentIndex === '' || !this.confirmModal ) return;
      // let exp = this.grouped[this.currentMonth];
      let index = this.expenses.indexOf(this.currentIndex);
      // console.log('modalYes', index, 'this.currentIndex', this.currentIndex, 'this.currentMonth', this.currentMonth);

      if (index<0) return;
      this.expenses.splice(index, 1);
      delete_item('/expenses/'+this.currentIndex.id);
      this.fGroup();
    },


    deleteRow(month, index){
        this.currentMonth = month;
        this.currentIndex = index;
        this.confirmModal = true;
        console.log('this.confirmModal' ,this.confirmModal);
    },

    deleteLink(id){
      return "/expenses/" + id 
    }


  }

})


</script>

app/views/expenses/_rows.html.slim
.panel.panel-default.expenses_table.expenses
  .panel-heading.table-heading.grid_title Расходы по категориям:
  
  template v-for="(item, index) in expense_rows"  
    ul v-show="!item._destroy"
      input type="hidden" :name="row_field(index,'expense_type_id')" :value="item.expense_type.value"
      input type="hidden" :name="row_field(index,'amount')" :value="item.amount"
      input type="hidden" :name="row_field(index,'comment')" :value="item.comment"
      input type="hidden" :name="row_field(index,'id')" v-if="item.id!==undefined" :value="item.id"
      input type="hidden" :name="row_field(index,'_destroy')" :value="item._destroy"
      li
        .expense_rows
          div 
            |{{item.expense_type.label}}
          .td_right
            |{{item.amount}}
          div 
            |{{item.comment}}
          div
            span.icon.icon_del @click="del_row(index)"
  .expense_rows.new_row   

      div
        = hidden_field 'expense_row', 'expense_id', value: @expense.id
        .inp_l.inp_w
          v-chosen name="new_expense_type" placeholder="Вид расхода"
      div
        m-number name="new_amount", "@input"=>"onInput()"
      div
        = text_field_tag :new_comment, '', class: 'txt', "v-model"=>"new_comment", "v-on:input"=>"onInput()"
      div
        span.btn_a.btn v-on:click="add_row" :disabled="!rowValid" Добавить

app/views/expenses/edit.html.erb
<h1>Редактирование расхода</h1>

<%= render 'form', expense: @expense %>

app/views/expenses/index.html.slim
.head
  | Расходы
  = link_to 'Добавить расход', new_expense_path, class: 'btn btn_a right'

.ower  
  .expenses
    .table_filter
      div
        v-chosen name="shop" placeholder="Магазин..." 
      div
        v-chosen name="account" placeholder="Счет..." 
      div
        v-chosen name="expense_type" placeholder="Вид расхода..."
      div
        v-chosen name="expense_kind" placeholder="Тип расхода..."
      div
        button @click="clearAll()" Сбросить  

    = render 'shared/index'
    = render 'shared/modal_delete'
= render 'index_vue'

app/views/expenses/new.html.erb
<h1>Новый расход</h1>

<%= render 'form', expense: @expense %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @expense.shop %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Account:</strong>
  <%= @expense.account %>
</p>

<p>
  <strong>Expense type:</strong>
  <%= @expense.expense_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @expense.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @expense.comment %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>